import React from 'react'

function BodyText() {
    return (
        <div className="BodyText">
            <h1>This is a Body Heading</h1>
            <p>Dizzle ipsum dolizzle sit amizzle, you son of a bizzle adipiscing my shizz. Bizzle bow wow wow velizzle, dizzle volutpat, suscipizzle quis, gravida vizzle, arcu. Pellentesque eget tortor. Sed erizzle. Dawg at fo shizzle my nizzle dapibizzle owned fo shizzle tellivizzle. Maurizzle pellentesque nibh et turpizzle. Stuff in for sure. Pellentesque eleifend rhoncizzle nisi. In fo shizzle mah nizzle fo rizzle, mah home g-dizzle habitasse platea dictumst. Pizzle crazy. Things tellus urna, pretizzle away, mattis ac, ass shizznit, nunc. Fo shizzle my nizzle dope. Integizzle sempizzle doggy sizzle fo.
            <br/><br/>
            Sizzle ullamcorper. Aliquizzle stuff massa doggy mauris. Vestibulizzle ante fo primizzle in faucibus orci luctizzle i saw beyonces tizzles and my pizzle went crizzle ultrices cool yo Fo shizzle mah nizzle fo rizzle, mah home g-dizzle; Daahng dawg vestibulum. Pellentesque fizzle morbi tristique fo shizzle break yo neck, yall netus break yo neck, yall malesuada fames ma nizzle break it down egestas. Donec tempor hendrerizzle ghetto. Aliquizzle erizzle i saw beyonces tizzles and my pizzle went crizzle. Vivamus fizzle doggy, fo izzle, shut the shizzle up a, fringilla vel, arcu. Nulla pimpin'. Donizzle fermentizzle, away brizzle pharetra aliquet, its fo rizzle erat hizzle shut the shizzle up, nizzle break yo neck, yall urna phat quizzle nibh. Vivamizzle izzle neque, shizzle my nizzle crocodizzle ut, ornare at, brizzle fo shizzle, pot. Bling bling purus sizzle, shizzle my nizzle crocodizzle sizzle amet, interdum check out this, dignissizzle break yo neck, yall, arcu. Yo mamma egizzle ipsum for sure est ullamcorpizzle tincidunt. Yippiyo quam. Mauris dizzle urna, tempor dang, scelerisque venenatizzle, sodales nec, i'm in the shizzle. Check out this fizzle.
            <br/><br/>
            Nunc fo shizzle mah nizzle fo rizzle, mah home g-dizzle lorizzle, pulvinar izzle, condimentum boofron, dang izzle, dizzle. Etiam sizzle leo shizzlin dizzle sizzle hendrerit sure. Black things izzle eros check it out owned. Etizzle fo shizzle my nizzle fermentizzle ligula. Morbi odio. Maecenizzle yo metizzle ac dolor sheezy auctizzle. Rizzle sagittizzle viverra urna. Crunk sollicitudizzle massa quizzle purus. Nizzle venenatis ligula gangster amizzle black. We gonna chung lobortizzle enizzle vitae arcu. Cum sociis natoque funky fresh da bomb magnizzle dizzle parturient fo shizzle mah nizzle fo rizzle, mah home g-dizzle, pot ridiculizzle mizzle.
            <br/><br/>
            Fo shizzle izzle metizzle at fizzle interdizzle aliquizzle. Dang posuere. Sizzle nizzle ante. Its fo rizzle ghetto go to hizzle, hendrerit fizzle, fo ass, uhuh ... yih! ma nizzle, massa. Vestibulizzle feugiat. Ut vehicula ultricizzle crunk. Fizzle vulputate, orci a fo shizzle dizzle, break it down lacizzle gizzle fo, izzle eleifend fo shizzle nulla nec fo shizzle mah nizzle fo rizzle, mah home g-dizzle. Maecenas break yo neck, yall bow wow wow i saw beyonces tizzles and my pizzle went crizzle. Daahng dawg neque mauris, mammasay mammasa mamma oo sa doggy, malesuada you son of a bizzle, bibendizzle shit, break yo neck, yall. Gizzle check out this, fo vel fo shizzle mah nizzle fo rizzle, mah home g-dizzle hendrerit, velit nibh doggy shit, crunk tempizzle justo lorizzle sit amet augue. Yo mamma check it out lacizzle nizzle odio fermentizzle dignissim. That's the shizzle aliquizzle sure yippiyo. Nizzle crunk shiznit maurizzle. Yo vehicula. Crizzle placerizzle bizzle a that's the shizzle. Etiam my shizz. In fo shizzle habitasse platea check it out. Cras fizzle leo nizzle fo nizzle shiznit. Phasellizzle funky fresh ante, dawg quis, fringilla a, owned nizzle, mah nizzle. Morbi vel nibh dizzle neque shizzle my nizzle crocodizzle fringilla.
            </p>
        </div>
    )
}

export default BodyText
